import os
import markdown
import datetime
from backend.schemas.analysis import AnalysisResponse

class HTMLRenderer:
    def __init__(self):
        self.assets_dir = os.path.join(os.path.dirname(__file__), "assets")
        self.css_path = os.path.join(self.assets_dir, "styles.css")
        self.logo_path = os.path.join(self.assets_dir, "logo.png")

    def read_css(self) -> str:
        if os.path.exists(self.css_path):
            with open(self.css_path, "r", encoding="utf-8") as f:
                return f.read()
        return ""

    def render(self, analysis: AnalysisResponse, image_base64: str = None) -> str:
        report_md = analysis.professional_report or analysis.gpt_analysis or "*No professional report available.*"
        report_html = markdown.markdown(report_md, extensions=["tables"])
        
        css = self.read_css()
        now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        
        image_html = ""
        if image_base64:
            if not image_base64.startswith("data:image"):
                image_base64 = f"data:image/jpeg;base64,{image_base64}"
            image_html = f"""
            <div class="satellite-image">
                <img src="{image_base64}" alt="Uploaded Satellite Image" />
                <div class="satellite-caption">Uploaded Satellite Image</div>
            </div>
            """
            
        logo_uri = ""
        if os.path.exists(self.logo_path):
            logo_uri = self.logo_path.replace("\\", "/")
            if not logo_uri.startswith("/"):
                logo_uri = "/" + logo_uri

        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>NovaAI Report</title>
            <style>
                {css}
            </style>
        </head>
        <body>
            <div id="header_content" class="report-header">
                NovaAI | Earth Observation Intelligence Platform
            </div>
            <div id="footer_content" class="report-footer">
                <table width="100%">
                    <tr>
                        <td align="left">Generated by NovaAI | {now}</td>
                        <td align="right">Page <pdf:pagenumber> of <pdf:pagecount> | v1.0</td>
                    </tr>
                </table>
            </div>

            <div class="cover-page">
                <img class="cover-logo" src="file://{logo_uri}" />
                <div class="cover-title">Earth Observation Report</div>
                <div class="cover-subtitle">Professional Intelligence Analysis</div>
                <p>Generated: {now}</p>
            </div>
            
            <pdf:nextpage />
            
            <div class="summary-card">
                <h3>EO Summary</h3>
                <p><strong>Dominant Land Cover:</strong> {analysis.dominant_land_cover}</p>
                <p><strong>Secondary Land Cover:</strong> {analysis.secondary_land_cover or "None"}</p>
                <p><strong>Confidence:</strong> {analysis.confidence}</p>
                <p><strong>Summary:</strong> {analysis.summary}</p>
            </div>
            
            {image_html}
            
            <div class="markdown-content">
                {report_html}
            </div>

            <pdf:nextpage />

            <h2>Technical Metadata</h2>
            <table class="metadata-table">
                <tr><th>Vision Model</th><td>{analysis.metadata.vision_model}</td></tr>
                <tr><th>Analysis Model</th><td>{analysis.metadata.llm_model}</td></tr>
                <tr><th>Report Model</th><td>{analysis.metadata.report_model or 'N/A'}</td></tr>
                <tr><th>Processing Time</th><td>{analysis.metadata.processing_time_ms} ms</td></tr>
                <tr><th>Generation Date</th><td>{analysis.metadata.timestamp}</td></tr>
                <tr><th>API Version</th><td>{analysis.metadata.version}</td></tr>
            </table>

        </body>
        </html>
        """
        
        return html_content

html_renderer = HTMLRenderer()
