/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LegacyLandingRouteImport } from './routes/legacy-landing'
import { Route as AichatRouteImport } from './routes/aichat'
import { Route as IndexRouteImport } from './routes/index'

const LegacyLandingRoute = LegacyLandingRouteImport.update({
  id: '/legacy-landing',
  path: '/legacy-landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AichatRoute = AichatRouteImport.update({
  id: '/aichat',
  path: '/aichat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aichat': typeof AichatRoute
  '/legacy-landing': typeof LegacyLandingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aichat': typeof AichatRoute
  '/legacy-landing': typeof LegacyLandingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aichat': typeof AichatRoute
  '/legacy-landing': typeof LegacyLandingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aichat' | '/legacy-landing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aichat' | '/legacy-landing'
  id: '__root__' | '/' | '/aichat' | '/legacy-landing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AichatRoute: typeof AichatRoute
  LegacyLandingRoute: typeof LegacyLandingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/legacy-landing': {
      id: '/legacy-landing'
      path: '/legacy-landing'
      fullPath: '/legacy-landing'
      preLoaderRoute: typeof LegacyLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aichat': {
      id: '/aichat'
      path: '/aichat'
      fullPath: '/aichat'
      preLoaderRoute: typeof AichatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AichatRoute: AichatRoute,
  LegacyLandingRoute: LegacyLandingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
