"""
analysis.py
-----------
Unified production-ready response schemas for the completed EO Analysis pipeline.
These models represent the final API shapes returned to the frontend.
"""

from pydantic import BaseModel, Field
from typing import Optional, Any


class AnalysisMetadata(BaseModel):
    """
    Request-level provenance and performance metadata.
    Returned alongside every production AnalysisResponse.
    """
    vision_model: str = Field(..., description="RemoteCLIP model identifier used for inference.")
    llm_model: str = Field(..., description="GPT/LLM model identifier used for analysis.")
    processing_time_ms: float = Field(..., description="Total end-to-end pipeline time in milliseconds.")
    timestamp: str = Field(..., description="ISO-8601 UTC timestamp of when the request was processed.")
    version: str = Field(default="1.0", description="API response schema version.")


class AnalysisResponse(BaseModel):
    """
    Unified production response for POST /api/analyze.

    Contains:
    - EO semantic classification (dominant/secondary land cover, confidence)
    - Rule-based scene summary from the interpreter
    - GPT-generated analyst report (or null with a warning if LLM unavailable)
    - Request metadata (model provenance, timing, timestamp)

    Raw vision-layer internals (embeddings, cosine similarities, logits)
    are NOT included here — they remain exclusive to /api/vision/test.
    """
    status: str = Field(
        ...,
        description="Pipeline outcome: 'success' or 'partial_success' (GPT unavailable)."
    )
    dominant_land_cover: str = Field(
        ...,
        description="The primary mapped Earth Observation category detected in the image."
    )
    secondary_land_cover: Optional[str] = Field(
        None,
        description="The secondary mapped category, or None if not applicable/undetermined."
    )
    confidence: str = Field(
        ...,
        description="Relative confidence qualitative band: High | Medium | Low."
    )
    summary: str = Field(
        ...,
        description="Rule-aligned static text summary generated from core semantics."
    )
    gpt_analysis: Optional[str] = Field(
        None,
        description="Reasoned interpretation report generated by GPT. Null if LLM failed."
    )
    warning: Optional[str] = Field(
        None,
        description="Present when status is 'partial_success'. Describes why GPT was skipped."
    )
    metadata: AnalysisMetadata = Field(
        ...,
        description="Request-level provenance, model info, and performance metrics."
    )
