"""
analysis.py
-----------
Unified production-ready response schemas for the completed EO Analysis pipeline.
These models represent the final API shapes returned to the frontend.
"""

from pydantic import BaseModel, Field
from typing import Optional


class AnalysisResponse(BaseModel):
    """
    Unified feedback result containing both structured computer-vision semantics
    and natural language LLM analysis.
    """
    dominant_land_cover: str = Field(
        ...,
        description="The primary mapped Earth Observation category detected in the image."
    )
    secondary_land_cover: Optional[str] = Field(
        None,
        description="The secondary mapped category, or None if not applicable/undetermined."
    )
    confidence: str = Field(
        ...,
        description="Relative confidence qualitative band: High | Medium | Low."
    )
    summary: str = Field(
        ...,
        description="Rule-aligned static text summary generated from core semantics."
    )
    gpt_analysis: str = Field(
        ...,
        description="Reasoned interpretation report generated by GPT using the underlying context."
    )
